// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-3')['BButton']
    BCol: typeof import('bootstrap-vue-3')['BCol']
    BContainer: typeof import('bootstrap-vue-3')['BContainer']
    BFormInput: typeof import('bootstrap-vue-3')['BFormInput']
    BListGroup: typeof import('bootstrap-vue-3')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-3')['BListGroupItem']
    BRow: typeof import('bootstrap-vue-3')['BRow']
    IMdiAdd: typeof import('~icons/mdi/add')['default']
    IMdiBaselineAdd: typeof import('~icons/mdi/baseline-add')['default']
    IMdiDelete: typeof import('~icons/mdi/delete')['default']
    IMdiDeleteOutline: typeof import('~icons/mdi/delete-outline')['default']
    IMdiOutlineAdd: typeof import('~icons/mdi/outline-add')['default']
    IMdiOutlineDelete: typeof import('~icons/mdi/outline-delete')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
